# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 999
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
    groups:
      artifacts:
        patterns:
          - "actions/*-artifact"
          - "dawidd6/action-download-artifact"
      caches:
        patterns:
          - "actions/cache"
          - "actions/cache/*"
      sast:
        patterns:
          - "github/codeql-*"
          - "actions/dependency-review-action"
          - "step-security/*"
          - "microsoft/security-devops-action'
          - 'microsoft/DevSkim-Action"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 999
    groups:
      mkdocs-core:
        patterns:
          - "mkdocs"
          - "mkdocs-material"
          - "mkdocs-material[*"
          - "CairoSVG"
          - "Pillow"
      mkdocs-plugins:
        patterns:
          - "pymdown-extensions"
          - "mkdocs-*"
          - "toc"
          - "setuptools"
        exclude-patterns:
          - "mkdocs-material"
          - "mkdocs-material*"
