site_name: Recipes
site_url: !ENV [SITE_URL, CF_PAGES_URL, 'https://recipes.demosjarco.dev']
site_author: DemosJarco
repo_name: demosjarco/recipes
repo_url: https://github.com/demosjarco/recipes
edit_uri: edit/main/recipes/
docs_dir: recipes
theme:
  name: material
  favicon: icon.png
  logo: icon.png
  icon:
    repo: fontawesome/brands/github
  # Enables highlighting of source code in code blocks using the highlight.js JavaScript library
  highlightjs: true
  # Lists the homepage in the sidebar menu. As MkDocs requires that the homepage be listed in the nav configuration option, this setting allows the homepage to be included or excluded from the sidebar. Note that the site name/logo always links to the homepage.
  include_homepage_in_sidebar: false
  # One of bottom, top, both , or none. Displays the “Next” and “Previous” buttons accordingly
  prev_next_buttons_location: none
  # The maximum depth of the navigation tree in the sidebar. Default: 4
  navigation_depth: 5
  # Only include the page section headers in the sidebar for the current page
  collapse_navigation: true
  # Only include page titles in the sidebar, excluding all section headers for all pages
  titles_only: false
  # If True, causes the sidebar to scroll with the main page content as you scroll the page
  sticky_navigation: true
  # The locale (language/location) used to build the theme. If your locale is not yet supported, it will fallback to the default
  locale: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Red Hat Mono
  features:
    # - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  custom_dir: overrides
extra:
  alternate:
    - name: English
      lang: 'en'
      link: '%GT_RELATIVE_URL%'  # For relative urls back to original language
    - name: Romanian
      lang: 'ro'
      link: !ENV [RO_TRANSLATE_URL, 'https://translate.google.com/translate?sl=en&tl=ro&hl=ro&u=https://recipes.demosjarco.dev/%GT_RELATIVE_URL%']
      # _x_tr_sl = source language
      # _x_tr_tl = translation language
      # _x_tr_hl = google translate ui language
    - name: Spanish
      lang: 'es'
      link: !ENV [ES_TRANSLATE_URL, 'https://translate.google.com/translate?sl=en&tl=es&hl=es&u=https://recipes.demosjarco.dev/%GT_RELATIVE_URL%']
      # _x_tr_sl = source language
      # _x_tr_tl = translation language
      # _x_tr_hl = google translate ui language
  social:
    - icon: fontawesome/solid/server
      link: https://recipes.demosjarco.dev
      name: Main
    - icon: fontawesome/brands/github
      link: https://demosjarco.github.io/recipes/
      name: GitHub Pages
    - icon: fontawesome/brands/cloudflare
      link: https://vic-recipes.pages.dev
      name: Cloudflare Pages
extra_javascript:
  - javascripts/keep_awake.js
extra_css:
  - stylesheets/full_width.css
markdown_extensions:
  - smarty
  - toc:
      permalink: "#"
      separator: "_"
  - sane_lists
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - tags
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
        reduce_boolean_attributes: true
      minify_js: true
      minify_css: true
      js_files:
        - javascripts/keep_awake.js
      css_files:
        - stylesheets/full_width.css
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, false]
  - glightbox
  - google-translate
  # - privacy:
  #     enabled: !ENV [CF_PAGES, GITHUB_ACTIONS, false]