# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate Docs

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v1
      with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
        # cache: true
    
    # Temp
    # - run: go install github.com/nicholaswilde/cook-docs/cmd/cook-docs@latest
    - run: go install
    - run: go mod tidy
    - run: ls -lA
    - run: cat go.mod
    - run: cat go.sum

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Setup
      run: python3 setup.py
    - name: Deploy
      run: mkdocs gh-deploy --help