name: Generate Docs
concurrency: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - "_headers"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      pages: write
    steps:
      - uses: step-security/harden-runner@v2.0.0
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.x'
          check-latest: true
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/setup-go@v3.4.0
        with:
          go-version: '1.x'
          check-latest: true
          # Must be disabled when no `go.sum`
          # cache: true
      - name: MkDocs cache
        uses: actions/cache@v3.0.11
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: mkdocs gh-deploy --force
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ENABLED_SOCIAL: true
            SITE_URL: https://demosjarco.github.io/recipes/
            RO_TRANSLATE_URL: https://translate.google.com/translate?sl=en&tl=ro&hl=ro&u=https://demosjarco.github.io/recipes/%GT_RELATIVE_URL%
            ES_TRANSLATE_URL: https://translate.google.com/translate?sl=en&tl=es&hl=es&u=https://demosjarco.github.io/recipes/%GT_RELATIVE_URL%