name: Generate Docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - "_headers"
  workflow_dispatch:
concurrency: ${{ github.ref }}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
    - uses: step-security/harden-runner@v1
      with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - uses: actions/cache@v2
      with:
        key: ${{ github.ref }}
        path: .cache
    - run: pip install -r requirements.txt
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
        # Must be disabled when no `go.sum`
        # cache: true
    - run: python3 setup.py
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}