name: Deploy
concurrency: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "_headers"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      pages: write
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          check-latest: true
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          check-latest: true
          # Must be disabled when no `go.sum`
          # cache: true
      - name: MkDocs cache
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLED_SOCIAL: true
          SITE_URL: https://demosjarco.github.io/recipes/
          RO_TRANSLATE_URL: https://translate.google.com/translate?sl=en&tl=ro&hl=ro&u=https://demosjarco.github.io/recipes/%GT_RELATIVE_URL%
          ES_TRANSLATE_URL: https://translate.google.com/translate?sl=en&tl=es&hl=es&u=https://demosjarco.github.io/recipes/%GT_RELATIVE_URL%
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: ${{ github.workspace }}/site/
          if-no-files-found: error
  lhci:
    name: Lighthouse
    needs: deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        formFactor: [mobile, desktop]
        include:
          # # Using iPhone 14 size https://blisk.io/devices/details/iphone-14
          - formFactor: mobile
            width: 390
            height: 844
            deviceScaleFactor: 3
            mobile: true
          - formFactor: desktop
            width: 1920
            height: 1080
            deviceScaleFactor: 1
            mobile: false
    steps:
      - uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install -D @lhci/cli@latest
      - run: npx lhci collect --settings.formFactor ${{ matrix.formFactor }} --settings.screenEmulation.width ${{ matrix.width }} --settings.screenEmulation.height ${{ matrix.height }} --settings.screenEmulation.deviceScaleFactor ${{ matrix.deviceScaleFactor }} --settings.screenEmulation.mobile ${{ matrix.mobile }}
      - run: npx lhci assert
      - run: npx lhci upload --githubStatusContextSuffix /${{ matrix.formFactor }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}